language: node_js
node_js:
  - '11'
install: npm install
script:
  - npm run build_prod
before_deploy:
  - cd dist/schoolboys
  - git init
deploy:
  provider: azure_web_apps
  verbose: true
  on:
    branch: master
  skip_cleanup: true